# Generated by Django 2.1.3 on 2020-03-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(default=False, max_length=15),
        ),
    ]
