# Generated by Django 2.1.3 on 2020-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
